### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by EltonZhong** [TinkoffCreditSystems/allure-android#12]
![image](https://user-images.githubusercontent.com/20570738/47342350-18125480-d6d6-11e8-8fde-deede0db6e52.png)
Got lots of errors, and don't know if this project is being maintained.

**Comment by EltonZhong** [comment]
Seems that it is not working well now...

**Comment by DDeg** [comment]
> ![image](https://user-images.githubusercontent.com/20570738/47342350-18125480-d6d6-11e8-8fde-deede0db6e52.png)
> Got lots of errors, and don't know if this project is being maintained.

This issue can be reproduces only on Android 8.0+ (API 26 or higher) because of changing how external storage works with permissions.
You can use device/emulator with Android version below 8.0 or just create folder 'allure-results' manually on external storage on Android 8.0+.
I'va handled this issue with custom Gradle script that call 'adb shell mkdir /sdcard/allure-results'

**Comment by EltonZhong** [comment]
> > ![image](https://user-images.githubusercontent.com/20570738/47342350-18125480-d6d6-11e8-8fde-deede0db6e52.png)
> > Got lots of errors, and don't know if this project is being maintained.
> 
> This issue can be reproduces only on Android 8.0+ (API 26 or higher) because of changing how external storage works with permissions.
> You can use device/emulator with Android version below 8.0 or just create folder 'allure-results' manually on external storage on Android 8.0+.
> I'va handled this issue with custom Gradle script that call 'adb shell mkdir /sdcard/allure-results'

Thanks.
